---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Where is the Space Station?
description: Plot the exact location of the ISS.
original_url: https://codeclubprojects.org/en-GB/python/iss
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introduction
- title: Who is in Space?
- title: 'Challenge: Show the Craft'
- title: Where is the ISS?
- title: When will the ISS be overhead?
- title: 'Challenge: Find more passover times'

