title: Where is the Space Station?
hero_image: images/banner.png
description: Plot the exact location of the ISS.
original_url:
theme: cc-prototype
listed: false
ingredient: false
duration: 1
interests:
technology: "python"
steps:
  - title: "Introduction"
  - title: "What you will need"
  - title: "Who is in Space?"
  - title: "Challenge: Show the Craft"
  - title: "Where is the ISS?"
  - title: "When will the ISS be overhead?"
  - title: "Challenge: Find more passover times"
