title: Where is the Space Station?
hero_image: images/banner.png
subtitle: Where is the Space Station?
description: Use Scratch to make a boat race game
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: cc-prototype
published: false
steps:
  - title: "Introduction"
    duration: 1
  - title: "What you will need"
    duration: 1
  - title: "Who is in Space?"
    duration: 1
  - title: "Challenge: Show the Craft"
    duration: 1
  - title: "Where is the ISS?"
    duration: 1
  - title: "Challenge: Find more passover times"
    duration: 1
